### ISSUE TITLE
Fewer than expected results from API?

### ISSUE THREAD

**Issue by ardian-c** [jobapis/jobs-ziprecruiter#7]
Hi,

I'm using the Ziprecruiter API for my application, and when fetching data from API, for a query say location: "Victoria, British Columbia", I get only 73 results from 100, but when searching through their site I can get 650+ job applications.

Am I missing something,?

Thanks

**Comment by karllhughes** [comment]
Hey @ardian-c I'm not sure about this. What happens if you call the API using curl or Postman rather than the PHP API client?

If it's a problem with not all jobs being included in the API you'll have to contact Ziprecruiter directly as I'm not affiliated with them. If, however, it's a problem with our PHP client I can start looking into this. Thanks for reporting the issue!

**Comment by ardian-c** [comment]
Hey @karllhughes I'm investigating this issue. I tried direct calls to Ziprecruiter API and I got the same (73) results, so there must be an issue/constraint on their side. I'll keep you updated if package needs any change in this aspect. Thanks!

**Comment by karllhughes** [comment]
Thanks for checking @ardian-c. I'll close this issue for now then.
